/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import logica.Pago;
import logica.Factura;


/**
 *
 * @author lucas
 */
public class InsertarVenta extends javax.swing.JFrame {
    /**
     * Creates new form Factura
     */
    public InsertarVenta() {
        initComponents();
        setTitle("Gym107");
        setIconImage();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_metodoPago = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcheck_asesoramiento = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtf_cvu = new javax.swing.JTextField();
        jtf_alias = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_numeroTarjeta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtf_cuentaBancaria = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbt_guardar = new javax.swing.JButton();
        jtf_codCliente = new javax.swing.JTextField();
        jtf_codMaquina = new javax.swing.JTextField();
        jtf_valorAsesoramiento = new javax.swing.JTextField();
        jtf_montoTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Insertar nueva venta");

        jtf_metodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Mercado Pago", "Transferencia", "Debito" }));
        jtf_metodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_metodoPagoActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo del ciente");

        jLabel3.setText("Codigo de la maquina");

        jcheck_asesoramiento.setText("Asesoramiento");
        jcheck_asesoramiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheck_asesoramientoActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor asesoramiento");

        jLabel5.setText("Monto Total");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel6.setText("CVU");

        jtf_cvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cvuActionPerformed(evt);
            }
        });

        jtf_alias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_aliasActionPerformed(evt);
            }
        });

        jLabel7.setText("Alias");

        jtf_numeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_numeroTarjetaActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero de Tarjeta");

        jtf_cuentaBancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cuentaBancariaActionPerformed(evt);
            }
        });

        jLabel9.setText("Cuenta Bancaria");

        jbt_guardar.setBackground(new java.awt.Color(141, 185, 81));
        jbt_guardar.setText("Guardar");
        jbt_guardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbt_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_guardarMouseClicked(evt);
            }
        });

        jtf_valorAsesoramiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_valorAsesoramientoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcheck_asesoramiento)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_valorAsesoramiento, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_metodoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_montoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_codCliente)
                                    .addComponent(jtf_codMaquina, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_cvu)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_cuentaBancaria)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_alias)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_numeroTarjeta, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jbt_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_metodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_codCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_codMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jcheck_asesoramiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_valorAsesoramiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_montoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_cvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_numeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_cuentaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbt_guardar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_metodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_metodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_metodoPagoActionPerformed

    private void jcheck_asesoramientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheck_asesoramientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcheck_asesoramientoActionPerformed

    private void jtf_cvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cvuActionPerformed

    private void jtf_aliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_aliasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_aliasActionPerformed

    private void jtf_numeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_numeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_numeroTarjetaActionPerformed

    private void jtf_cuentaBancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cuentaBancariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cuentaBancariaActionPerformed

    private void jbt_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_guardarMouseClicked
        Factura factura = new Factura();
        Pago pago = new Pago();
        
        boolean error = false;
        pago.tipo = (String) jtf_metodoPago.getSelectedItem();
        if(jtf_codCliente.getText().isEmpty()){
            error = true;
        }else{
            factura.codCli = Integer.parseInt(jtf_codCliente.getText());
        }
        if(jtf_codMaquina.getText().isEmpty()){
            error = true;
        }else{
            factura.codMaquina = Integer.parseInt(jtf_codMaquina.getText());
        }
        if(jcheck_asesoramiento.isSelected()) {
            factura.valorAsesoramiento = Integer.parseInt(jtf_valorAsesoramiento.getText());
        }else{
            factura.valorAsesoramiento = 0;
        }
        if(jtf_montoTotal.getText().isEmpty()){
            error = true;
        }else{
            factura.montoFinal = Integer.parseInt(jtf_montoTotal.getText());
            pago.monto = Integer.parseInt(jtf_montoTotal.getText());
        }
        if(jtf_cvu.getText().isEmpty()){
            error = true;
        }else{
            pago.cvu = Integer.parseInt(jtf_cvu.getText());
        }
        if(jtf_alias.getText().isEmpty()){
            error = true;
        }else{
            pago.alias = jtf_alias.getText();
        }
        if(jtf_numeroTarjeta.getText().isEmpty()){
            error = true;
        }else{
            pago.numTarjeta = Integer.parseInt(jtf_numeroTarjeta.getText());
        }
        if(jtf_cuentaBancaria.getText().isEmpty()){
            error = true;
        }else{
            pago.cuentaBancaria = Integer.parseInt(jtf_cuentaBancaria.getText());
        }        
        if(!error){
            JOptionPane.showMessageDialog(null, "Datos enviados a la Base de Datos");
            
            factura.insertarFactura();
            pago.insertarPago();

        }
        if(error){
            JOptionPane.showMessageDialog(null, "El formulario esta incompleto o alguno de sus datos es incorrecto");
            error = false;
        }    }//GEN-LAST:event_jbt_guardarMouseClicked

    private void jtf_valorAsesoramientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_valorAsesoramientoKeyTyped
        char c = evt.getKeyChar();
        if(!jcheck_asesoramiento.isSelected()){
            evt.consume();
        }
    }//GEN-LAST:event_jtf_valorAsesoramientoKeyTyped
        private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("107.jpg")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbt_guardar;
    private javax.swing.JCheckBox jcheck_asesoramiento;
    private javax.swing.JTextField jtf_alias;
    private javax.swing.JTextField jtf_codCliente;
    private javax.swing.JTextField jtf_codMaquina;
    private javax.swing.JTextField jtf_cuentaBancaria;
    private javax.swing.JTextField jtf_cvu;
    private javax.swing.JComboBox<String> jtf_metodoPago;
    private javax.swing.JTextField jtf_montoTotal;
    private javax.swing.JTextField jtf_numeroTarjeta;
    private javax.swing.JTextField jtf_valorAsesoramiento;
    // End of variables declaration//GEN-END:variables
}
